apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: taskapi-staging
nameSuffix: "-canary"
  track: canary
resources:
  - ../../base
patches:
  - path: patches/canary-patch.yaml
    target:
      kind: Deployment
      name: taskapi
images:
  - name: ghcr.io/ajay263/taskapi
    newName: ghcr.io/ajay263/taskapi
    newTag: latest
  - name: taskapi
    newName: ghcr.io/ajay263/taskapi
    newTag: latest
