apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: taskapi-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: taskapi.availability
      interval: 30s
      rules:

        - alert: TaskAPIDown
          expr: up{job="taskapi"} == 0
          for: 1m
          labels:
            severity: critical
            namespace: "{{ $labels.namespace }}"
          annotations:
            summary: "🔴 TaskAPI is DOWN in {{ $labels.namespace }}"
            description: "TaskAPI has been unreachable for 1+ minute. Immediate action required."
            runbook_url: "https://github.com/Ajay263/taskapi-gitops/blob/main/docs/runbooks/taskapi-down.md"

        - alert: TaskAPIHighErrorRate
          expr: |
            (
              rate(taskapi_requests_total{http_status=~"5.."}[5m])
              /
              rate(taskapi_requests_total[5m])
            ) > 0.05
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "⚠️ High error rate in {{ $labels.namespace }}"
            description: "Error rate is {{ $value | humanizePercentage }} over the last 5 minutes."

        - alert: TaskAPISlowResponses
          expr: |
            histogram_quantile(0.95,
              sum(rate(taskapi_request_duration_seconds_bucket[5m]))
              by (le, namespace)
            ) > 0.5
          for: 10m
          labels:
            severity: warning
          annotations:
            summary: "⚠️ p95 latency > 500ms in {{ $labels.namespace }}"
            description: "95th percentile latency is {{ $value | humanizeDuration }}. SLO breach imminent."

        - alert: TaskAPIPodsNotReady
          expr: |
            kube_deployment_status_replicas_ready{deployment="taskapi"}
            < kube_deployment_spec_replicas{deployment="taskapi"}
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "⚠️ TaskAPI pods degraded in {{ $labels.namespace }}"
            description: "{{ $value }} pods ready, expected more. Check pod events."

        - alert: TaskAPIMemoryNearLimit
          expr: |
            container_memory_working_set_bytes{container="taskapi"}
            / container_spec_memory_limit_bytes{container="taskapi"} > 0.85
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "⚠️ TaskAPI memory above 85% in {{ $labels.namespace }}"
            description: "Memory usage is {{ $value | humanizePercentage }} of limit. Risk of OOMKill."