---
- name: Add Argo Helm repo
  kubernetes.core.helm_repository:
    name: argo
    repo_url: https://argoproj.github.io/argo-helm

- name: Install ArgoCD via Helm
  kubernetes.core.helm:
    name: argocd
    chart_ref: argo/argo-cd
    chart_version: "{{ argocd_helm_version }}"
    release_namespace: argocd
    create_namespace: true
    values:
      server:
        service:
          type: NodePort
          nodePort: 30444
      redis:
        enabled: true
    wait: true
    timeout: "300s"

- name: Wait for ArgoCD server
  kubernetes.core.k8s_info:
    kind: Deployment
    name: argocd-server
    namespace: argocd
    wait: true
    wait_condition:
      type: Available
      status: "True"
    wait_timeout: 180

- name: Get ArgoCD admin password
  ansible.builtin.shell: |
    kubectl -n argocd get secret argocd-initial-admin-secret \
      -o jsonpath="{.data.password}" | base64 -d
  register: argocd_password
  changed_when: false

- name: Add GitOps repository to ArgoCD via kubectl
  ansible.builtin.shell: |
    kubectl create secret generic argocd-repo-taskapi-gitops       --namespace argocd       --from-literal=type=git       --from-literal=url={{ argocd_repo_url }}       --from-literal=username=Ajay263       --from-literal=password={{ argocd_repo_token }}       --dry-run=client -o yaml |     kubectl annotate --local -f -       managed-by=argocd.argoproj.io       --dry-run=client -o yaml |     kubectl label --local -f -       argocd.argoproj.io/secret-type=repository       --dry-run=client -o yaml |     kubectl apply -f -
  changed_when: true
  no_log: true

- name: Debug file paths
  ansible.builtin.debug:
    msg:
      - "role_path: {{ role_path }}"
      - "playbook_dir: {{ playbook_dir }}"
      - "project file: {{ playbook_dir }}/../../argocd/projects/taskapi-project.yaml"

- name: Apply ArgoCD AppProject
  kubernetes.core.k8s:
    state: present
    src: "{{ playbook_dir }}/../../argocd/projects/taskapi-project.yaml"

- name: Patch AppProject to allow ClusterSecretStore
  kubernetes.core.k8s_json_patch:
    kind: AppProject
    name: taskapi
    namespace: argocd
    patch:
      - op: add
        path: /spec/clusterResourceWhitelist/-
        value:
          group: external-secrets.io
          kind: ClusterSecretStore

- name: Apply ArgoCD application
  kubernetes.core.k8s:
    state: present
    src: "{{ role_path }}/../../../argocd/apps/taskapi-dev.yaml"

- name: Sync ArgoCD app
  ansible.builtin.command: >
    argocd app sync taskapi-dev --insecure
  changed_when: false
  ignore_errors: true

- name: Show ArgoCD status
  ansible.builtin.command: >
    argocd app get taskapi-dev --insecure
  register: argocd_status
  changed_when: false

- name: Display ArgoCD app status
  ansible.builtin.debug:
    msg: "{{ argocd_status.stdout_lines }}"