apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: taskapi
  namespace: argocd
spec:
  description: TaskAPI platform — dev, staging, prod
  sourceRepos:
    - https://github.com/Ajay263/taskapi-gitops
    - https://github.com/Ajay263/taskapi
  destinations:
    - namespace: taskapi-dev
      server: https://kubernetes.default.svc
    - namespace: taskapi-staging
      server: https://kubernetes.default.svc
    - namespace: taskapi-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: external-secrets.io
      kind: ClusterSecretStore
    - group: policy
      kind: PodDisruptionBudget
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  orphanedResources:
    warn: true
