apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapi-staging
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: taskapi
  source:
    repoURL: https://github.com/Ajay263/taskapi-gitops
    targetRevision: HEAD
    path: taskapi-gitops/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: taskapi-staging
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
