apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapi-staging
  namespace: argocd
spec:
  project: taskapi
  source:
    repoURL: https://github.com/ajay263/taskapi-gitops
    targetRevision: HEAD
    path: taskapi-gitops/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: taskapi-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true